/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package samplegradle;

import model.Instrument;
import model.TradingPhase;
import simulation.BaseSimulation;
import simulation.asia.jp.JPSimulation;

public class App {
    private static boolean testSimulation(BaseSimulation simulation, Instrument instrument) {
        return simulation.shouldQueue(instrument);
    }

    public String getGreeting() {
        return "Hello";
    }

    public static void main(String[] args) {
        Instrument instrument = new Instrument("7752.T");
        instrument.setTradingPhase(TradingPhase.Halted);
        
        System.out.println( String.format("Should Queue: %b", testSimulation( new JPSimulation(), instrument)));
    }
}
